# Generated by Django 3.0.5 on 2020-11-08 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20201108_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='subtopico',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Subtopico', verbose_name='Subtópico'),
        ),
    ]
