# Generated by Django 3.0.5 on 2020-11-08 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0003_auto_20201108_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tema',
            options={'ordering': ['topico'], 'verbose_name': 'Tema', 'verbose_name_plural': 'Temas'},
        ),
        migrations.AlterField(
            model_name='tema',
            name='subtopico',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Subtopico', verbose_name='Subtópico'),
        ),
        migrations.CreateModel(
            name='DetalleTema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado_por')),
                ('subtopico', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Subtopico', verbose_name='Subtópico')),
                ('tema', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Tema', verbose_name='Tema')),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Topico', verbose_name='Tópico')),
            ],
            options={
                'verbose_name': 'Detalle de Tema',
                'verbose_name_plural': 'Detalle de Temas',
                'ordering': ['topico'],
            },
        ),
    ]
