# Generated by Django 3.0.5 on 2020-11-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20201108_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tema',
            options={'ordering': ['topico', 'subtopico'], 'verbose_name': 'Tema', 'verbose_name_plural': 'Temas'},
        ),
        migrations.AlterField(
            model_name='detalletema',
            name='descripcion',
            field=models.TextField(default='', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='topico',
            name='imagen',
            field=models.ImageField(upload_to='topicos', verbose_name='Imagen'),
        ),
    ]
