# Generated by Django 3.0.5 on 2020-11-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20201120_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopico',
            name='imagen',
            field=models.ImageField(null=True, upload_to='topicos', verbose_name='Imagen'),
        ),
    ]
