# Generated by Django 3.0.5 on 2020-11-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_subtopico_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='imagen',
            field=models.ImageField(null=True, upload_to='temas', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='subtopico',
            name='imagen',
            field=models.ImageField(null=True, upload_to='subtopicos', verbose_name='Imagen'),
        ),
    ]
