# Generated by Django 3.0.5 on 2020-11-22 23:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20201122_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalletema',
            name='descripcion',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Descripción'),
        ),
    ]
