# Generated by Django 3.0.5 on 2021-02-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_topico_url_infografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='url_infografia',
            field=models.URLField(null=True, verbose_name='URL Infografía'),
        ),
    ]
