# Generated by Django 3.0.5 on 2021-02-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_tema_url_infografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='url_infografia',
            field=models.URLField(blank=True, null=True, verbose_name='URL Infografía'),
        ),
    ]
