# Generated by Django 3.0.5 on 2020-12-26 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0011_auto_20201224_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='estado_civil',
            field=models.CharField(choices=[('Casado', 'Casado(a)'), ('Viudo', 'Viudo(a)'), ('Soltero', 'Soltero(a)')], default='Soltero', max_length=10, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='respuestanpi',
            name='r10b',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='10b'),
        ),
        migrations.AlterField(
            model_name='respuestanpi',
            name='r11b',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='11b'),
        ),
        migrations.AlterField(
            model_name='respuestanpi',
            name='r12b',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='12b'),
        ),
        migrations.AlterField(
            model_name='respuestanpi',
            name='r1b',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='1b'),
        ),
        migrations.AlterField(
            model_name='respuestanpi',
            name='r2b',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='2b'),
        ),
        migrations.AlterField(
            model_name='respuestanpi',
            name='r3b',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='3b'),
        ),
        migrations.AlterField(
            model_name='respuestanpi',
            name='r4b',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='4b'),
        ),
        migrations.AlterField(
            model_name='respuestanpi',
            name='r5b',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='5b'),
        ),
        migrations.AlterField(
            model_name='respuestanpi',
            name='r6b',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='6b'),
        ),
        migrations.AlterField(
            model_name='respuestanpi',
            name='r7b',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='7b'),
        ),
        migrations.AlterField(
            model_name='respuestanpi',
            name='r8b',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='8b'),
        ),
        migrations.AlterField(
            model_name='respuestanpi',
            name='r9b',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='9b'),
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.PositiveIntegerField(verbose_name='Edad')),
                ('estado_civil', models.CharField(max_length=10, verbose_name='Estado Civil')),
                ('tipo', models.CharField(max_length=10, verbose_name='Tipo de Cuidador')),
                ('relacion_paciente', models.CharField(max_length=20, verbose_name='Relación con paciente')),
                ('fecha_cuidado', models.DateField(verbose_name='Inicio de cuidadoS')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuidador',
                'verbose_name_plural': 'Cuidadores',
            },
        ),
    ]
