# Generated by Django 4.1 on 2023-05-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_auto_20201226_0414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respuestanpi',
            options={'ordering': ['-id'], 'verbose_name': 'Respuesta NPI', 'verbose_name_plural': 'Respuestas NPI'},
        ),
        migrations.AlterModelOptions(
            name='respuestazarit',
            options={'ordering': ['-id'], 'verbose_name': 'Respuesta Zarit', 'verbose_name_plural': 'Respuestas Zarit'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['-fecha'], 'verbose_name': 'Test', 'verbose_name_plural': 'Tests'},
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='fecha_cuidado',
            field=models.DateField(verbose_name='Inicio de cuidados'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado_civil',
            field=models.CharField(choices=[('Casado', 'Casado(a)'), ('Soltero', 'Soltero(a)'), ('Viudo', 'Viudo(a)')], default='Soltero', max_length=10, verbose_name='Estado Civil'),
        ),
    ]
