# Generated by Django 4.1 on 2023-05-16 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0013_alter_respuestanpi_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuidador',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuidadores', to=settings.AUTH_USER_MODEL, verbose_name='Médico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado_civil',
            field=models.CharField(choices=[('Casado', 'Casado(a)'), ('Viudo', 'Viudo(a)'), ('Soltero', 'Soltero(a)')], default='Soltero', max_length=10, verbose_name='Estado Civil'),
        ),
    ]
