# Generated by Django 4.1 on 2023-05-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_cuidador_medico_alter_paciente_estado_civil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='estado_civil',
        ),
        migrations.AddField(
            model_name='paciente',
            name='enfermedades',
            field=models.CharField(default='Ninguna', max_length=15, verbose_name='Enfermedades'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_de_nacimiento',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de nacimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(default=0, max_length=10, verbose_name='Sexo'),
            preserve_default=False,
        ),
    ]
