# Generated by Django 4.1 on 2023-05-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_remove_paciente_estado_civil_paciente_enfermedades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='enfermedades',
            field=models.CharField(default='Ninguna', max_length=100, verbose_name='Enfermedades'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_de_nacimiento',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
    ]
