# Generated by Django 4.1 on 2023-05-24 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0016_alter_paciente_enfermedades_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_baño', models.PositiveIntegerField(verbose_name='Frecuencia de baño')),
                ('f_alimentacion', models.PositiveIntegerField(verbose_name='Frecuencia de alimentación')),
                ('f_sueño', models.PositiveIntegerField(verbose_name='Frecuencia de sueño')),
                ('animo', models.PositiveIntegerField(verbose_name='Estado de ánimo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
