# Generated by Django 4.1 on 2023-05-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
    ]
