# Generated by Django 4.1 on 2023-05-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0018_evento_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha de Creación'),
        ),
    ]
