# Generated by Django 4.1 on 2023-05-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_alter_evento_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='comentario',
            field=models.TextField(default='', max_length=200, verbose_name='Otro'),
        ),
    ]
