# Generated by Django 4.1 on 2023-05-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0020_evento_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='f_sueño',
            field=models.PositiveIntegerField(verbose_name='Horas de sueño'),
        ),
    ]
