# Generated by Django 4.1 on 2023-05-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0021_alter_evento_f_sueño'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='comentario',
            field=models.TextField(default='', max_length=200, null=True, verbose_name='Otro'),
        ),
    ]
