# Generated by Django 4.1 on 2023-05-25 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0022_alter_evento_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.cuidador'),
        ),
    ]
