# Generated by Django 4.1 on 2023-05-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0025_alter_evento_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='f_baño',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Frecuencia de baño'),
        ),
    ]
