# Generated by Django 4.1 on 2023-05-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0026_alter_evento_f_baño'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='f_baño',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Frecuencia de baño'),
        ),
    ]
