# Generated by Django 4.1 on 2023-05-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0027_alter_evento_f_baño'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='animo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Estado de ánimo'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='f_alimentacion',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Frecuencia de alimentación'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='f_sueño',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Horas de sueño'),
        ),
    ]
