# Generated by Django 4.1 on 2023-05-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0028_alter_evento_animo_alter_evento_f_alimentacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
